import 'package:flutter_workout_app/model/training_model.dart';

List<TrainingModel> listWorkout = [
  TrainingModel(
    title: 'Your Full Marathon Training Plan - 20 Weeks',
    image: './assets/images/exercise_1.jpg',
    date: 'May 30, 2021',
    comments: 19,
    running: true,
    training: true,
  ),
  TrainingModel(
    title: 'Marathon Training Guide For (Total) Beginners',
    image: './assets/images/exercise_2.jpg',
    date: 'May 20, 2021',
    comments: 5,
    running: true,
    training: true,
  ),
  TrainingModel(
    title: 'Biceps exercises for Men',
    image: './assets/images/exercise_3.jpg',
    date: 'May 20, 2021',
    comments: 19,
    training: true,
  ),
  TrainingModel(
    title: 'How To Get Back Into Weight Training And Lifting After A ..',
    image: './assets/images/exercise_4.jpg',
    date: 'May 30, 2021',
    comments: 19,
    cardio: true,
    training: true,
  ),
  TrainingModel(
    title: 'Your Full Marathon Training Plan - 20 Weeks',
    image: './assets/images/exercise_1.jpg',
    date: 'May 30, 2021',
    comments: 19,
    running: true,
    training: true,
  ),
  TrainingModel(
    title: 'Marathon Training Guide For (Total) Beginners',
    image: './assets/images/exercise_2.jpg',
    date: 'May 20, 2021',
    comments: 5,
    running: true,
    training: true,
  ),
  TrainingModel(
    title: 'Biceps exercises for Men',
    image: './assets/images/exercise_3.jpg',
    date: 'May 20, 2021',
    comments: 19,
    training: true,
  ),
  TrainingModel(
    title: 'How To Get Back Into Weight Training And Lifting After A ..',
    image: './assets/images/exercise_4.jpg',
    date: 'May 30, 2021',
    comments: 19,
    cardio: true,
    training: true,
  ),
];
